// <auto-generated />
using System;
using System.Collections.Generic;
using CositadeZacatlan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CositadeZacatlan.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CositadeZacatlan.Domain.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Amenities")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Accommodations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000001"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 1850m,
                            Capacity = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña Vista a la Niebla: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña Vista a la Niebla",
                            Slug = "cabana-vista-a-la-niebla",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000002"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 3200m,
                            Capacity = 8,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña El Bosque Encantado: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña El Bosque Encantado",
                            Slug = "cabana-el-bosque-encantado",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000003"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 2100m,
                            Capacity = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña Manzana Dorada: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña Manzana Dorada",
                            Slug = "cabana-manzana-dorada",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000004"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 2500m,
                            Capacity = 6,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña El Nido del Águila: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña El Nido del Águila",
                            Slug = "cabana-el-nido-del-aguila",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000005"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 1950m,
                            Capacity = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña Los Pinos Altos: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña Los Pinos Altos",
                            Slug = "cabana-los-pinos-altos",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000006"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 2300m,
                            Capacity = 5,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña Rincón del Fuego: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña Rincón del Fuego",
                            Slug = "cabana-rincon-del-fuego",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000007"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 2700m,
                            Capacity = 6,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña Valle del Sol: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña Valle del Sol",
                            Slug = "cabana-valle-del-sol",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-000000000008"),
                            Amenities = new List<string> { "Chimenea", "Jacuzzi", "Wi-Fi Starlink", "Terraza Privada", "Asador" },
                            BasePrice = 2900m,
                            Capacity = 8,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cabaña La Barranca: Cabaña de montaña equipada con chimenea a leña, terraza privada y vistas espectaculares a la sierra de Zacatlán.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Cabaña La Barranca",
                            Slug = "cabana-la-barranca",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000001"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 1350m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Manzanas de Oro: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Manzanas de Oro",
                            Slug = "suite-manzanas-de-oro",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000002"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 1470m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Niebla Matutina: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Niebla Matutina",
                            Slug = "suite-niebla-matutina",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000003"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 1590m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Sidra Artesanal: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Sidra Artesanal",
                            Slug = "suite-sidra-artesanal",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000004"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 1710m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Reloj de Flores: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Reloj de Flores",
                            Slug = "suite-reloj-de-flores",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000005"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 1830m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Barranca de los Jilgueros: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Barranca de los Jilgueros",
                            Slug = "suite-barranca-de-los-jilgueros",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000006"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 1950m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Los Cedros: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Los Cedros",
                            Slug = "suite-los-cedros",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000007"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 2070m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Sol de Montaña: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Sol de Montaña",
                            Slug = "suite-sol-de-montana",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000008"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 2190m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Luna de Pino: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Luna de Pino",
                            Slug = "suite-luna-de-pino",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000009"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 2310m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Piedra Volcánica: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Piedra Volcánica",
                            Slug = "suite-piedra-volcanica",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000010"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 2430m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite El Mirador: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite El Mirador",
                            Slug = "suite-el-mirador",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000011"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 2550m,
                            Capacity = 2,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Arcilla & Leña: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Arcilla & Leña",
                            Slug = "suite-arcilla-y-lena",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-000000000012"),
                            Amenities = new List<string> { "Cama King Size", "Calefacción Rústica", "Cata de Sidra de Bienvenida", "Room Service" },
                            BasePrice = 2670m,
                            Capacity = 4,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Suite Presidencial Zacatlán: Suite de lujo en nuestro Hotel Boutique con acabados artesanales y cama King Size.",
                            ImageUrls = new List<string>(),
                            IsActive = true,
                            Name = "Suite Presidencial Zacatlán",
                            Slug = "suite-presidencial-zacatlan",
                            Type = 2
                        });
                });

            modelBuilder.Entity("CositadeZacatlan.Domain.Entities.BlockedDate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("BlockedDates");
                });

            modelBuilder.Entity("CositadeZacatlan.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccommodationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccommodationId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CositadeZacatlan.Domain.Entities.BlockedDate", b =>
                {
                    b.HasOne("CositadeZacatlan.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany("BlockedDates")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("CositadeZacatlan.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CositadeZacatlan.Domain.Entities.Accommodation", "Accommodation")
                        .WithMany("Bookings")
                        .HasForeignKey("AccommodationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Accommodation");
                });

            modelBuilder.Entity("CositadeZacatlan.Domain.Entities.Accommodation", b =>
                {
                    b.Navigation("BlockedDates");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
